### ISSUE TITLE
Art issue tracker

### ISSUE THREAD

**Issue by TheArturZh** [Sierra-14/Emblazed#12]
- [ ] I need to figure out what palettes to use, preferably pick something that at least remotely looks like Bay12 palettes
- [ ] I need to repalette some of the tg stuff, starting with wood tiles
- [ ] I need to take Sierra sprites (those that aren't ugly) and fix/redraw some stuff so it works with hybrid perspective
