### ISSUE TITLE
Megawalls issue tracker

### ISSUE THREAD

**Issue by TheArturZh** [Sierra-14/Emblazed#9]
- [ ] Need a missing state failsafes for both megawalls and smoothicons
- [ ] Maybe Megawall perspective switch point should match FOV overlay toggle point so transition looks smoother
- [ ] Make FOV overlay work properly for no-rot objects (airlocks and rotated walls at their current stage shouldn't look weird)
